export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-3xl">
      <h1 className="text-5xl font-bangers text-primary tracking-wider mb-8">Terms of Service</h1>
      <div className="prose prose-invert lg:prose-lg font-sans">
        <p>By using Comic Strip Creator, you agree to these terms.</p>
        <h2 className="text-2xl font-bangers mt-8 mb-4">Usage</h2>
        <p>You may use the tool to create comics for personal or commercial use. You retain ownership of the content you create.</p>
        <h2 className="text-2xl font-bangers mt-8 mb-4">Assets</h2>
        <p>The placeholder assets provided within the app are free to use within the context of the comics generated by this tool.</p>
      </div>
    </div>
  );
}
