const { chromium } = require('playwright');
const assert = require('assert');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  const urlsToTest = [
    'http://localhost:3000/blog/how-to-write-webtoon-script',
    'http://localhost:3000/genres/webtoon-romance-comic-creator',
    'http://localhost:3000/genres/action-webtoon-comic-maker',
    'http://localhost:3000/genres/thriller-webtoon-generator',
    'http://localhost:3000/layouts/infinite-scroll-comic-layout',
    'http://localhost:3000/layouts/mobile-first-comic-layout',
    'http://localhost:3000/layouts/stacked-panel-comic-layout',
    'http://localhost:3000/styles/modern-webtoon-comic-style',
    'http://localhost:3000/styles/flat-color-comic-style',
    'http://localhost:3000/blog/comic-shading-lighting-guide',
    'http://localhost:3000/genres/cyberpunk-romance-comic-creator',
    'http://localhost:3000/genres/high-school-drama-comic-generator',
    'http://localhost:3000/genres/medical-drama-comic-maker',
    'http://localhost:3000/layouts/3x4-grid-comic-layout',
    'http://localhost:3000/layouts/diagonal-split-panel-layout',
    'http://localhost:3000/layouts/hexagonal-panel-comic-layout',
    'http://localhost:3000/styles/cyber-noir-comic-style',
    'http://localhost:3000/styles/retro-manga-comic-style',
    'http://localhost:3000/blog/comic-panel-transitions-guide',
    'http://localhost:3000/genres/autobiographical-comic-maker',
    'http://localhost:3000/genres/gag-a-day-comic-creator',
    'http://localhost:3000/genres/surreal-comic-generator',
    'http://localhost:3000/layouts/15-panel-grid-comic',
    'http://localhost:3000/layouts/borderless-panel-comic-layout',
    'http://localhost:3000/layouts/tilted-panel-comic-layout',
    'http://localhost:3000/styles/woodcut-comic-style',
    'http://localhost:3000/styles/synthwave-comic-style',
    'http://localhost:3000/use-cases',
    'http://localhost:3000/techniques',
    'http://localhost:3000/genres',
    'http://localhost:3000/genres/neon-noir-comic-maker',
    'http://localhost:3000/genres/cyberpunk-color-comic-maker',
    'http://localhost:3000/genres/pastel-slice-of-life-comic',
    'http://localhost:3000/layouts/splash-page-layout-comic',
    'http://localhost:3000/blog/comic-anatomy-proportions-guide',
    'http://localhost:3000/genres/post-cyberpunk-comic-maker',
    'http://localhost:3000/genres/magic-realism-comic-creator',
    'http://localhost:3000/genres/superhero-origin-comic-maker',
    'http://localhost:3000/genres/detective-noir-comic-generator',
    'http://localhost:3000/layouts/comic-book-spread-layout',
    'http://localhost:3000/layouts/diamond-panel-comic-layout',
    'http://localhost:3000/layouts/honeycomb-panel-comic-layout',
    'http://localhost:3000/styles/gritty-comic-style',
    'http://localhost:3000/blog/comic-composition-perspective-guide',
    'http://localhost:3000/genres/mecha-comic-maker',
    'http://localhost:3000/genres/sports-comic-creator',
    'http://localhost:3000/genres/historical-fiction-comic-maker',
    'http://localhost:3000/layouts/splash-page-comic-layout',
    'http://localhost:3000/layouts/comic-book-cover-layout',
    'http://localhost:3000/layouts/2x2-grid-comic-layout',
    'http://localhost:3000/styles/comic-book-inking-style',
    'http://localhost:3000/styles/manga-shojo-style-creator',
    'http://localhost:3000/blog/mastering-comic-pacing-guide',
    'http://localhost:3000/genres/mythology-comic-maker',
    'http://localhost:3000/genres/fairy-tale-comic-creator',
    'http://localhost:3000/genres/dystopian-comic-generator',
    'http://localhost:3000/genres/space-opera-comic-builder',
    'http://localhost:3000/layouts/16-panel-grid-comic',
    'http://localhost:3000/layouts/circular-panel-comic-layout',
    'http://localhost:3000/layouts/irregular-panel-comic-layout',
    'http://localhost:3000/styles/line-art-comic-creator',
    'http://localhost:3000/blog/comic-background-design-guide',
    'http://localhost:3000/genres/supernatural-comic-maker',
    'http://localhost:3000/genres/steampunk-comic-creator',
    'http://localhost:3000/genres/zombie-comic-generator',
    'http://localhost:3000/genres/post-apocalyptic-comic-maker',
    'http://localhost:3000/layouts/10-panel-comic-layout',
    'http://localhost:3000/layouts/12-panel-grid-comic',
    'http://localhost:3000/layouts/diagonal-panel-comic',
    'http://localhost:3000/styles/manga-shonen-style-creator',
    'http://localhost:3000/blog/advanced-dialogue-techniques',
    'http://localhost:3000/genres/western-comic-maker',
    'http://localhost:3000/genres/mystery-comic-maker',
    'http://localhost:3000/genres/slice-of-life-comic-creator',
    'http://localhost:3000/genres/educational-comic-generator',
    'http://localhost:3000/layouts/1-panel-gag-cartoon',
    'http://localhost:3000/layouts/5-panel-comic-layout',
    'http://localhost:3000/layouts/9-panel-grid-comic',
    'http://localhost:3000/styles/pop-art-comic-maker',
    'http://localhost:3000/blog/comic-strip-guide',
    'http://localhost:3000/genres/superhero-comic-maker',
    'http://localhost:3000/genres/manga-style-comic',
    'http://localhost:3000/genres/humor-comic-strip',
    'http://localhost:3000/genres/fantasy-adventure-comic',
    'http://localhost:3000/layouts/3-panel-comic',
    'http://localhost:3000/layouts/4-panel-comic',
    'http://localhost:3000/layouts/6-panel-comic',
    'http://localhost:3000/styles/chibi-character-creator',
    'http://localhost:3000/blog/comic-color-theory-guide',
    'http://localhost:3000/genres/noir-comic-maker',
    'http://localhost:3000/genres/romance-comic-creator',
    'http://localhost:3000/genres/horror-comic-generator',
    'http://localhost:3000/genres/sci-fi-comic-builder',
    'http://localhost:3000/layouts/vertical-scroll-comic',
    'http://localhost:3000/layouts/2-panel-comic-layout',
    'http://localhost:3000/styles/pixel-art-comic-creator',
    'http://localhost:3000/styles/webtoon-style-comic-maker',
    'http://localhost:3000/genres/thriller-comic-maker',
    'http://localhost:3000/genres/cyberpunk-comic-creator',
    'http://localhost:3000/genres/historical-comic-generator',
    'http://localhost:3000/genres/parody-comic-maker',
    'http://localhost:3000/layouts/7-panel-comic',
    'http://localhost:3000/layouts/8-panel-grid',
    'http://localhost:3000/layouts/infinite-canvas-comic',
    'http://localhost:3000/styles/watercolor-comic-creator',
    'http://localhost:3000/blog/digital-coloring-techniques-guide',
    'http://localhost:3000/genres/action-comic-maker',
    'http://localhost:3000/genres/comedy-comic-creator',
    'http://localhost:3000/layouts/5-panel-horizontal-layout',
    'http://localhost:3000/layouts/10-panel-grid-layout',
    'http://localhost:3000/styles/watercolor-comic-style',
    'http://localhost:3000/styles/pop-art-comic-style',
    'http://localhost:3000/styles/pixel-art-style',
    'http://localhost:3000/styles/retro-comic-style',
    'http://localhost:3000/blog/comic-inking-rendering-guide',
    'http://localhost:3000/genres/cyberpunk-noir-comic-maker',
    'http://localhost:3000/genres/urban-fantasy-comic-creator',
    'http://localhost:3000/genres/historical-romance-comic-maker',
    'http://localhost:3000/genres/space-western-comic-generator',
    'http://localhost:3000/layouts/asymmetrical-panel-comic-layout',
    'http://localhost:3000/layouts/widescreen-comic-layout',
    'http://localhost:3000/layouts/overlapping-panel-comic',
    'http://localhost:3000/styles/vintage-newspaper-comic-style',
    'http://localhost:3000/blog/character-expressions-guide',
    'http://localhost:3000/genres/fantasy-romance-comic-maker',
    'http://localhost:3000/genres/sci-fi-comedy-comic-creator',
    'http://localhost:3000/genres/superhero-parody-comic-maker',
    'http://localhost:3000/layouts/3x3-grid-comic-layout',
    'http://localhost:3000/layouts/4x4-grid-comic-layout',
    'http://localhost:3000/layouts/7-panel-irregular-comic',
    'http://localhost:3000/styles/minimalist-comic-style',
    'http://localhost:3000/styles/gothic-comic-style',
    'http://localhost:3000/blog/comic-lettering-sound-effects-guide',
    'http://localhost:3000/genres/martial-arts-comic-maker',
    'http://localhost:3000/genres/vampire-comic-creator',
    'http://localhost:3000/genres/time-travel-comic-generator',
    'http://localhost:3000/genres/spy-espionage-comic-builder',
    'http://localhost:3000/layouts/circle-panel-comic',
    'http://localhost:3000/layouts/triangle-panel-comic',
    'http://localhost:3000/layouts/layered-panel-comic',
    'http://localhost:3000/styles/charcoal-comic-style',
      'http://localhost:3000/blog/comic-book-cover-design-guide',
    'http://localhost:3000/genres/superhero-team-comic-maker',
    'http://localhost:3000/genres/villain-origin-comic-creator',
    'http://localhost:3000/genres/cyberpunk-hacker-comic-generator',
    'http://localhost:3000/genres/high-fantasy-comic-builder',
    'http://localhost:3000/layouts/5x5-grid-comic-layout',
    'http://localhost:3000/layouts/panoramic-panel-comic',
    'http://localhost:3000/layouts/interlocking-panel-comic',
    'http://localhost:3000/styles/retro-sci-fi-comic-style',
    'http://localhost:3000/blog/dynamic-comic-poses-guide',
    'http://localhost:3000/genres/action-shonen-comic-maker',
    'http://localhost:3000/genres/magical-girl-comic-creator',
    'http://localhost:3000/genres/super-robot-comic-generator',
    'http://localhost:3000/genres/cyber-noir-comic-builder',
    'http://localhost:3000/layouts/dynamic-action-panel-layout',
    'http://localhost:3000/layouts/manga-action-lines-layout',
    'http://localhost:3000/layouts/character-focus-panel-layout',
    'http://localhost:3000/styles/dynamic-action-comic-style',

    'http://localhost:3000/blog/ultimate-guide-to-comic-strip-creation-in-2026',
    'http://localhost:3000/blog/comicflow-vs-canva',
    'http://localhost:3000/blog/what-is-a-comic-strip',
    'http://localhost:3000/blog/what-is-a-panel-in-comics',
    'http://localhost:3000/blog/what-is-a-speech-bubble',
    'http://localhost:3000/blog/what-is-a-caption-box',
    'http://localhost:3000/blog/what-is-a-gutter-in-comics',
    'http://localhost:3000/blog/how-to-monetize-a-webcomic',
    'http://localhost:3000/genres/comedy-romance-comic-maker',
    'http://localhost:3000/genres/isekai-comic-creator',
    'http://localhost:3000/genres/cyber-goth-comic-generator',
    'http://localhost:3000/genres/solarpunk-comic-maker',
    'http://localhost:3000/layouts/mobile-optimized-comic-layout',
    'http://localhost:3000/layouts/print-ready-comic-layout',
    'http://localhost:3000/layouts/webtoon-scroll-comic-layout',
    'http://localhost:3000/styles/neon-cyberpunk-comic-style',
      'http://localhost:3000/blog/graphic-novel-creation-guide',
    'http://localhost:3000/genres/graphic-novel-maker',
    'http://localhost:3000/genres/young-adult-comic-creator',
    'http://localhost:3000/genres/memoir-comic-builder',
    'http://localhost:3000/genres/historical-drama-comic-generator',
    'http://localhost:3000/layouts/chapter-based-comic-layout',
    'http://localhost:3000/layouts/double-page-spread-layout',
    'http://localhost:3000/layouts/graphic-novel-grid-layout',
    'http://localhost:3000/styles/ink-wash-comic-style',
    'http://localhost:3000/blog/visual-storytelling-comics-guide',
    'http://localhost:3000/genres/silent-comic-maker',
    'http://localhost:3000/genres/surreal-fantasy-comic-builder',
    'http://localhost:3000/genres/abstract-comic-creator',
    'http://localhost:3000/layouts/inset-panel-comic-layout',
    'http://localhost:3000/layouts/bleeding-panel-comic-layout',
    'http://localhost:3000/layouts/horizontal-scroll-comic-layout',
    'http://localhost:3000/styles/monochromatic-comic-style',
    'http://localhost:3000/styles/high-contrast-comic-style',
    'http://localhost:3000/blog/comic-world-building-guide',
    'http://localhost:3000/genres/sports-drama-comic-creator',
    'http://localhost:3000/genres/mythology-comic-maker',
    'http://localhost:3000/genres/culinary-comic-generator',
    'http://localhost:3000/genres/music-band-comic-creator',
    'http://localhost:3000/layouts/14-panel-grid-comic',
    'http://localhost:3000/layouts/pyramid-panel-layout',
    'http://localhost:3000/layouts/zigzag-panel-layout',
    'http://localhost:3000/styles/synthwave-comic-style',
  ];
  page.on('console', msg => {
    if (msg.type() === 'error') {
      console.error('Page Error: ' + msg.text());
    }
  });
  for (const url of urlsToTest) {
    console.log('Testing URL: ' + url);
    const response = await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
    if (response.status() !== 200) {
        console.error('Error: Expected status 200, but got ' + response.status() + ' for ' + url);
        process.exit(1);
    }
  }
  console.log('Testing editor functionality at /editor...');
  await page.goto('http://localhost:3000/editor', { waitUntil: 'networkidle' });
  try {
      // 1. Verify Panel Editor exists
      const panels = await page.locator('div[id^="panel-"]').all();
      console.log('Found ' + panels.length + ' panels.');
      assert(panels.length > 0, 'No comic panels found in editor.');
      // 2. Verify Asset Library loading (using text content in sidebars)
      const bodyText = await page.innerText('body');
      assert(bodyText.includes('Characters') || bodyText.includes('Props') || bodyText.includes('Assets'), 'Asset categories not found in editor.');
      // 3. Verify Export features
      const exportButtons = await page.locator('button').all();
      const exportTexts = await Promise.all(exportButtons.map(b => b.innerText()));
      const hasExport = exportTexts.some(text => text.includes('Export') || text.includes('PNG') || text.includes('PDF'));
      assert(hasExport, 'Export buttons not found.');
      console.log('✅ All core functionality checks passed.');
  } catch (error) {
      console.error('❌ Core functionality test failed: ' + error.message);
      process.exit(1);
  }
  await browser.close();
  console.log('All E2E tests completed successfully.');
})();
